<template>
  <div class="table">
    <div class="table__description mb-6">
      Dans cet exercice vous devez afficher les données <code>customers</code> dans un tableau en utilisant le composant
      Vuetify <a href="https://vuetifyjs.com/en/components/data-tables/" target="_blank"><code>v-data-table</code></a
      >.<br />
      Le but de cet exercice est d'évaluer votre capacité à prioriser une information et de l'afficher de façon
      pertinente. <br />
      Pour ce faire, vous devez rajouter le code manquant dans le fichier <code>src/views/Table.vue</code>. (ex: L'ID du
      client n'est pas une donnée pertinente à afficher.)<br />
      <em>
        Notes :
        <ul>
          <li>
            Les dates sont au format ISO et peuvent être manipulées avec
            <a href="https://day.js.org/" target="_blank">days.js</a> (déjà présent dans le projet).
          </li>
          <li>
            Les valeurs possible de la propriété <code>job</code> sont
            <code>developer, designer, sales ou humanResources</code>
          </li>
        </ul>
      </em>
    </div>
    <v-data-table class="table__data-table" :headers="headers" :items="customers"> </v-data-table>
  </div>
</template>

<script>
export default {
  name: 'Table',
  data() {
    return {
      headers: [],
      customers: [
        {
          _id: '60abca8793936f75410e832f',
          isActive: false,
          age: 29,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Charmaine',
            last: 'Wiley',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Charmaine+Wiley&rounded=true&size=24&background=random',
          company: 'BUGSALL',
          email: 'charmaine.wiley@bugsall.io',
          phone: '+33 (955) 424-2279',
          address: '915 Wortman Avenue, Jacksonwald, Oklahoma, 7259',
          registered: 'Tue Oct 30 2018 08:21:50 GMT+0000 (UTC)',
          lastConnection: 'Fri Mar 05 2021 17:34:46 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8769deaed66941db1c',
          isActive: true,
          age: 47,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Felecia',
            last: 'Rowland',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Felecia+Rowland&rounded=true&size=24&background=random',
          company: 'SOLAREN',
          email: 'felecia.rowland@solaren.com',
          phone: '+33 (952) 437-3006',
          address: '852 Riverdale Avenue, Savage, Utah, 4000',
          registered: 'Thu Sep 27 2018 19:16:23 GMT+0000 (UTC)',
          lastConnection: 'Tue Feb 09 2021 05:04:21 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8792bff0de40196488',
          isActive: true,
          age: 43,
          eyeColor: 'blue',
          job: 'designer',
          name: {
            first: 'Gwen',
            last: 'Morse',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Gwen+Morse&rounded=true&size=24&background=random',
          company: 'DOGNOST',
          email: 'gwen.morse@dognost.tv',
          phone: '+33 (962) 483-2480',
          address: '232 Dorchester Road, Alderpoint, Louisiana, 8330',
          registered: 'Thu Feb 28 2019 02:49:53 GMT+0000 (UTC)',
          lastConnection: 'Sun Feb 21 2021 21:46:30 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8796b2bf6ad3e4313e',
          isActive: true,
          age: 22,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Courtney',
            last: 'Ashley',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Courtney+Ashley&rounded=true&size=24&background=random',
          company: 'EXIAND',
          email: 'courtney.ashley@exiand.ca',
          phone: '+33 (936) 428-2049',
          address: '221 Elliott Walk, Berlin, Maine, 6834',
          registered: 'Mon Aug 05 2019 21:56:21 GMT+0000 (UTC)',
          lastConnection: 'Mon Jan 18 2021 23:04:48 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87bbbada2c4c54bd74',
          isActive: true,
          age: 23,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Barrera',
            last: 'Duncan',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Barrera+Duncan&rounded=true&size=24&background=random',
          company: 'COMVEX',
          email: 'barrera.duncan@comvex.name',
          phone: '+33 (946) 528-2252',
          address: '807 Bay Avenue, Oneida, South Carolina, 6317',
          registered: 'Fri Oct 25 2019 11:41:35 GMT+0000 (UTC)',
          lastConnection: 'Sun Apr 04 2021 08:56:15 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87b0c4178ccf8f95a2',
          isActive: false,
          age: 42,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Gregory',
            last: 'Becker',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Gregory+Becker&rounded=true&size=24&background=random',
          company: 'SUNCLIPSE',
          email: 'gregory.becker@sunclipse.co.uk',
          phone: '+33 (878) 492-2460',
          address: '868 Calder Place, Summertown, West Virginia, 1020',
          registered: 'Tue Dec 24 2019 02:23:34 GMT+0000 (UTC)',
          lastConnection: 'Wed Jan 27 2021 16:04:44 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87eae903cdc4887129',
          isActive: false,
          age: 30,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Jeanine',
            last: 'Stark',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Jeanine+Stark&rounded=true&size=24&background=random',
          company: 'OVOLO',
          email: 'jeanine.stark@ovolo.me',
          phone: '+33 (913) 573-2042',
          address: '139 Throop Avenue, Herbster, North Carolina, 2653',
          registered: 'Mon Jul 02 2018 19:15:27 GMT+0000 (UTC)',
          lastConnection: 'Sun Mar 14 2021 13:15:42 GMT+0000 (UTC)',
        },
        {
          _id: '60abca875c1d3887ae3bc22b',
          isActive: false,
          age: 50,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Sloan',
            last: 'Mcintosh',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Sloan+Mcintosh&rounded=true&size=24&background=random',
          company: 'SCHOOLIO',
          email: 'sloan.mcintosh@schoolio.us',
          phone: '+33 (958) 461-2002',
          address: '912 Summit Street, Eastvale, Rhode Island, 1281',
          registered: 'Thu Sep 05 2019 19:15:10 GMT+0000 (UTC)',
          lastConnection: 'Tue Apr 13 2021 14:26:12 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87544351b3356eb71b',
          isActive: true,
          age: 46,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Carver',
            last: 'Chaney',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Carver+Chaney&rounded=true&size=24&background=random',
          company: 'BEADZZA',
          email: 'carver.chaney@beadzza.info',
          phone: '+33 (951) 414-2326',
          address: '195 Clymer Street, Vivian, Florida, 1503',
          registered: 'Sat Jan 05 2019 08:23:55 GMT+0000 (UTC)',
          lastConnection: 'Thu Feb 25 2021 10:28:39 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87a4dfc93004b796ec',
          isActive: false,
          age: 46,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Carpenter',
            last: 'Brooks',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Carpenter+Brooks&rounded=true&size=24&background=random',
          company: 'SURETECH',
          email: 'carpenter.brooks@suretech.net',
          phone: '+33 (912) 470-3463',
          address: '815 Powers Street, Waikele, Connecticut, 8762',
          registered: 'Fri Mar 30 2018 03:30:35 GMT+0000 (UTC)',
          lastConnection: 'Tue May 11 2021 04:57:35 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87899d0475a5ba6fb3',
          isActive: false,
          age: 46,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Reyna',
            last: 'Kerr',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Reyna+Kerr&rounded=true&size=24&background=random',
          company: 'SOPRANO',
          email: 'reyna.kerr@soprano.biz',
          phone: '+33 (803) 558-3507',
          address: '319 Maple Avenue, Marshall, Alaska, 5049',
          registered: 'Mon Jul 22 2019 09:36:43 GMT+0000 (UTC)',
          lastConnection: 'Mon May 17 2021 05:42:40 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87999ff0efa87b8d30',
          isActive: false,
          age: 22,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Britney',
            last: 'Rivera',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Britney+Rivera&rounded=true&size=24&background=random',
          company: 'QUONK',
          email: 'britney.rivera@quonk.biz',
          phone: '+33 (965) 478-3894',
          address: '397 Manhattan Avenue, Coaldale, Massachusetts, 3876',
          registered: 'Thu Jun 21 2018 10:51:50 GMT+0000 (UTC)',
          lastConnection: 'Wed Jan 20 2021 01:55:16 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87b4a80d163d158e5a',
          isActive: false,
          age: 44,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Freida',
            last: 'Colon',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Freida+Colon&rounded=true&size=24&background=random',
          company: 'KANGLE',
          email: 'freida.colon@kangle.io',
          phone: '+33 (849) 432-3545',
          address: '407 Arlington Place, Leyner, Arkansas, 1055',
          registered: 'Tue Sep 11 2018 22:42:15 GMT+0000 (UTC)',
          lastConnection: 'Wed Feb 24 2021 11:50:05 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8748c776df083d6a9b',
          isActive: true,
          age: 33,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Mosley',
            last: 'Holt',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Mosley+Holt&rounded=true&size=24&background=random',
          company: 'ZORK',
          email: 'mosley.holt@zork.com',
          phone: '+33 (833) 593-2358',
          address: '538 Willoughby Avenue, Urbana, Nebraska, 1501',
          registered: 'Tue Oct 02 2018 00:31:52 GMT+0000 (UTC)',
          lastConnection: 'Mon Mar 22 2021 17:18:01 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87cdd66ef034191f74',
          isActive: true,
          age: 34,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Wilkinson',
            last: 'Perry',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Wilkinson+Perry&rounded=true&size=24&background=random',
          company: 'BULLJUICE',
          email: 'wilkinson.perry@bulljuice.tv',
          phone: '+33 (929) 509-2895',
          address: '708 Cumberland Street, Heil, Virginia, 3834',
          registered: 'Sat Nov 23 2019 19:19:44 GMT+0000 (UTC)',
          lastConnection: 'Tue Feb 23 2021 19:07:36 GMT+0000 (UTC)',
        },
        {
          _id: '60abca872c2324d75e61fd46',
          isActive: false,
          age: 40,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Osborn',
            last: 'Crane',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Osborn+Crane&rounded=true&size=24&background=random',
          company: 'LOTRON',
          email: 'osborn.crane@lotron.ca',
          phone: '+33 (964) 562-3194',
          address: '251 Schenectady Avenue, Carrizo, Minnesota, 7629',
          registered: 'Thu Mar 08 2018 09:48:16 GMT+0000 (UTC)',
          lastConnection: 'Fri Feb 12 2021 22:16:45 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8716c8719a3292b56c',
          isActive: true,
          age: 31,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Mays',
            last: 'Marsh',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Mays+Marsh&rounded=true&size=24&background=random',
          company: 'FUELTON',
          email: 'mays.marsh@fuelton.name',
          phone: '+33 (920) 566-3658',
          address: '395 Lynch Street, Gardners, New Jersey, 3806',
          registered: 'Wed Jan 03 2018 07:08:15 GMT+0000 (UTC)',
          lastConnection: 'Thu Mar 11 2021 12:34:41 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87f65b04b916ece794',
          isActive: true,
          age: 29,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Earnestine',
            last: 'Miranda',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Earnestine+Miranda&rounded=true&size=24&background=random',
          company: 'LIQUICOM',
          email: 'earnestine.miranda@liquicom.co.uk',
          phone: '+33 (841) 439-2436',
          address: '567 Heyward Street, Beyerville, Illinois, 6334',
          registered: 'Mon Aug 05 2019 02:49:22 GMT+0000 (UTC)',
          lastConnection: 'Wed Feb 17 2021 06:38:22 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87f7c6d7cc5c523ed5',
          isActive: false,
          age: 29,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Alba',
            last: 'Nicholson',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Alba+Nicholson&rounded=true&size=24&background=random',
          company: 'UNISURE',
          email: 'alba.nicholson@unisure.me',
          phone: '+33 (856) 567-2536',
          address: '373 Linwood Street, Brecon, Kentucky, 5341',
          registered: 'Tue Feb 12 2019 02:29:25 GMT+0000 (UTC)',
          lastConnection: 'Thu Mar 11 2021 08:16:44 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87e8eba373fcf5f708',
          isActive: true,
          age: 50,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Gertrude',
            last: 'Turner',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Gertrude+Turner&rounded=true&size=24&background=random',
          company: 'MOTOVATE',
          email: 'gertrude.turner@motovate.us',
          phone: '+33 (958) 510-2540',
          address: '823 Fillmore Place, Cochranville, New York, 8087',
          registered: 'Fri Nov 30 2018 23:37:31 GMT+0000 (UTC)',
          lastConnection: 'Fri Feb 19 2021 17:04:57 GMT+0000 (UTC)',
        },
        {
          _id: '60abca874e9e54d59b86b757',
          isActive: true,
          age: 26,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Mejia',
            last: 'Gallegos',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Mejia+Gallegos&rounded=true&size=24&background=random',
          company: 'JAMNATION',
          email: 'mejia.gallegos@jamnation.info',
          phone: '+33 (903) 495-3797',
          address: '234 Norwood Avenue, Jeff, Tennessee, 8075',
          registered: 'Tue May 29 2018 11:58:05 GMT+0000 (UTC)',
          lastConnection: 'Tue Mar 09 2021 07:02:18 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87333a4601c2242458',
          isActive: false,
          age: 44,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Cardenas',
            last: 'Dillon',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Cardenas+Dillon&rounded=true&size=24&background=random',
          company: 'COSMETEX',
          email: 'cardenas.dillon@cosmetex.net',
          phone: '+33 (991) 558-2916',
          address: '125 Shale Street, Hiseville, Wyoming, 151',
          registered: 'Wed Sep 04 2019 18:28:17 GMT+0000 (UTC)',
          lastConnection: 'Sat May 15 2021 22:26:59 GMT+0000 (UTC)',
        },
        {
          _id: '60abca874604607228247e2d',
          isActive: true,
          age: 40,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Lindsey',
            last: 'Franks',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Lindsey+Franks&rounded=true&size=24&background=random',
          company: 'ANIXANG',
          email: 'lindsey.franks@anixang.biz',
          phone: '+33 (985) 443-2408',
          address: '819 Brightwater Avenue, Southmont, Idaho, 6933',
          registered: 'Fri Jan 11 2019 09:19:21 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 01 2021 21:23:00 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87f2ca2607e43e41f7',
          isActive: false,
          age: 32,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Mcclain',
            last: 'Massey',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Mcclain+Massey&rounded=true&size=24&background=random',
          company: 'OPTICOM',
          email: 'mcclain.massey@opticom.biz',
          phone: '+33 (975) 451-2070',
          address: '617 Ridge Boulevard, Websterville, Georgia, 5502',
          registered: 'Sat Jul 07 2018 23:44:55 GMT+0000 (UTC)',
          lastConnection: 'Wed Feb 24 2021 22:00:41 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8796c7305332bedf4e',
          isActive: true,
          age: 43,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Inez',
            last: 'Sawyer',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Inez+Sawyer&rounded=true&size=24&background=random',
          company: 'ENDIPIN',
          email: 'inez.sawyer@endipin.io',
          phone: '+33 (848) 440-2634',
          address: '847 Montague Terrace, Fannett, Indiana, 394',
          registered: 'Tue Oct 30 2018 08:09:00 GMT+0000 (UTC)',
          lastConnection: 'Sun Apr 04 2021 17:27:57 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87ac5dca4303fc1333',
          isActive: false,
          age: 33,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Luann',
            last: 'Rivas',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Luann+Rivas&rounded=true&size=24&background=random',
          company: 'ASSISTIX',
          email: 'luann.rivas@assistix.com',
          phone: '+33 (907) 418-3054',
          address: '686 Canton Court, Fairview, California, 9210',
          registered: 'Thu Aug 29 2019 17:00:48 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 08 2021 03:34:15 GMT+0000 (UTC)',
        },
        {
          _id: '60abca870dfb935aa375b9b6',
          isActive: true,
          age: 39,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Tisha',
            last: 'Gillespie',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Tisha+Gillespie&rounded=true&size=24&background=random',
          company: 'RODEOCEAN',
          email: 'tisha.gillespie@rodeocean.tv',
          phone: '+33 (981) 407-3421',
          address: '811 Batchelder Street, Goochland, Pennsylvania, 141',
          registered: 'Mon Jan 15 2018 20:33:18 GMT+0000 (UTC)',
          lastConnection: 'Sun Mar 07 2021 03:04:29 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8775e6a383c924a638',
          isActive: false,
          age: 23,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Riddle',
            last: 'Burns',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Riddle+Burns&rounded=true&size=24&background=random',
          company: 'ECSTASIA',
          email: 'riddle.burns@ecstasia.ca',
          phone: '+33 (861) 589-3810',
          address: '461 Stockholm Street, Walland, Virgin Islands, 896',
          registered: 'Fri Nov 16 2018 19:02:13 GMT+0000 (UTC)',
          lastConnection: 'Wed Jan 06 2021 07:53:25 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8776a73989e355e1a9',
          isActive: false,
          age: 29,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'York',
            last: 'Brewer',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=York+Brewer&rounded=true&size=24&background=random',
          company: 'REMOLD',
          email: 'york.brewer@remold.name',
          phone: '+33 (994) 555-2928',
          address: '343 Conklin Avenue, Outlook, Texas, 1620',
          registered: 'Sat Jan 27 2018 05:11:56 GMT+0000 (UTC)',
          lastConnection: 'Tue Mar 23 2021 00:46:46 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87b1063ce07d8804eb',
          isActive: true,
          age: 38,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Andrea',
            last: 'Avila',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Andrea+Avila&rounded=true&size=24&background=random',
          company: 'LUNCHPOD',
          email: 'andrea.avila@lunchpod.co.uk',
          phone: '+33 (964) 458-2496',
          address: '913 Crown Street, Greenwich, Michigan, 3571',
          registered: 'Thu Apr 25 2019 10:32:49 GMT+0000 (UTC)',
          lastConnection: 'Mon May 10 2021 20:50:11 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87b205c6fd712b7c84',
          isActive: false,
          age: 23,
          eyeColor: 'blue',
          job: 'designer',
          name: {
            first: 'Elma',
            last: 'Bright',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Elma+Bright&rounded=true&size=24&background=random',
          company: 'TRANSLINK',
          email: 'elma.bright@translink.me',
          phone: '+33 (831) 450-3499',
          address: '992 Amherst Street, Idamay, Arizona, 7132',
          registered: 'Sat Apr 07 2018 11:26:20 GMT+0000 (UTC)',
          lastConnection: 'Mon Jan 18 2021 13:37:07 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87f553317134224361',
          isActive: true,
          age: 20,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Katheryn',
            last: 'Gordon',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Katheryn+Gordon&rounded=true&size=24&background=random',
          company: 'VENDBLEND',
          email: 'katheryn.gordon@vendblend.us',
          phone: '+33 (833) 568-3287',
          address: '479 Gem Street, Yonah, Nevada, 2181',
          registered: 'Thu May 10 2018 19:54:19 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 22 2021 06:35:24 GMT+0000 (UTC)',
        },
        {
          _id: '60abca870a36534003b7b8bd',
          isActive: false,
          age: 27,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Santiago',
            last: 'Cohen',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Santiago+Cohen&rounded=true&size=24&background=random',
          company: 'HARMONEY',
          email: 'santiago.cohen@harmoney.info',
          phone: '+33 (913) 575-2606',
          address: '688 Eldert Street, Tolu, Ohio, 7047',
          registered: 'Thu Sep 12 2019 10:56:36 GMT+0000 (UTC)',
          lastConnection: 'Mon Apr 12 2021 00:40:51 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8733fdc161c35f9292',
          isActive: false,
          age: 28,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Morrison',
            last: 'Bass',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Morrison+Bass&rounded=true&size=24&background=random',
          company: 'TELEPARK',
          email: 'morrison.bass@telepark.net',
          phone: '+33 (832) 442-3292',
          address: '887 Martense Street, Babb, Guam, 7975',
          registered: 'Sat Jun 08 2019 08:06:40 GMT+0000 (UTC)',
          lastConnection: 'Sun Apr 18 2021 15:03:10 GMT+0000 (UTC)',
        },
        {
          _id: '60abca870eb25fa7cbd917c2',
          isActive: true,
          age: 30,
          eyeColor: 'blue',
          job: 'designer',
          name: {
            first: 'Thompson',
            last: 'Herman',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Thompson+Herman&rounded=true&size=24&background=random',
          company: 'ZILLAR',
          email: 'thompson.herman@zillar.biz',
          phone: '+33 (905) 434-3976',
          address: '409 Seacoast Terrace, Chase, Montana, 1851',
          registered: 'Wed Aug 22 2018 00:13:52 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 22 2021 09:42:02 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87bf96dee1eead3ce8',
          isActive: false,
          age: 38,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Elba',
            last: 'Wynn',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Elba+Wynn&rounded=true&size=24&background=random',
          company: 'OZEAN',
          email: 'elba.wynn@ozean.biz',
          phone: '+33 (851) 570-2193',
          address: '180 Herbert Street, Tuskahoma, Missouri, 2871',
          registered: 'Sun Aug 12 2018 02:37:50 GMT+0000 (UTC)',
          lastConnection: 'Tue Apr 27 2021 11:31:05 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87178cc064b815516e',
          isActive: false,
          age: 41,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Lawson',
            last: 'Butler',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Lawson+Butler&rounded=true&size=24&background=random',
          company: 'ENTOGROK',
          email: 'lawson.butler@entogrok.io',
          phone: '+33 (879) 506-3744',
          address: '988 Durland Place, Bascom, Vermont, 6638',
          registered: 'Thu Sep 13 2018 05:36:03 GMT+0000 (UTC)',
          lastConnection: 'Thu Apr 22 2021 13:43:51 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87a45767817a46f625',
          isActive: false,
          age: 26,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Virginia',
            last: 'Bradshaw',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Virginia+Bradshaw&rounded=true&size=24&background=random',
          company: 'ECOLIGHT',
          email: 'virginia.bradshaw@ecolight.com',
          phone: '+33 (838) 514-2738',
          address: '188 Wakeman Place, Sunwest, Washington, 1716',
          registered: 'Sat Apr 13 2019 15:41:34 GMT+0000 (UTC)',
          lastConnection: 'Wed May 19 2021 09:44:14 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8710cf3d03e94e0431',
          isActive: true,
          age: 24,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Huff',
            last: 'Welch',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Huff+Welch&rounded=true&size=24&background=random',
          company: 'JOVIOLD',
          email: 'huff.welch@joviold.tv',
          phone: '+33 (856) 402-3012',
          address: '328 Holly Street, Craig, American Samoa, 2695',
          registered: 'Tue Dec 03 2019 05:47:29 GMT+0000 (UTC)',
          lastConnection: 'Sat May 01 2021 22:02:29 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87cf2b6ef49a068aa8',
          isActive: false,
          age: 48,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Francesca',
            last: 'Atkins',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Francesca+Atkins&rounded=true&size=24&background=random',
          company: 'GEEKOLOGY',
          email: 'francesca.atkins@geekology.ca',
          phone: '+33 (934) 498-2955',
          address: '119 Bulwer Place, Rosewood, Kansas, 7049',
          registered: 'Wed Nov 20 2019 03:10:39 GMT+0000 (UTC)',
          lastConnection: 'Sat Jan 23 2021 05:30:43 GMT+0000 (UTC)',
        },
        {
          _id: '60abca878f5404c152990759',
          isActive: false,
          age: 41,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Alexandra',
            last: 'Lancaster',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Alexandra+Lancaster&rounded=true&size=24&background=random',
          company: 'DUOFLEX',
          email: 'alexandra.lancaster@duoflex.name',
          phone: '+33 (843) 560-2781',
          address: '761 Fay Court, Loyalhanna, Palau, 1586',
          registered: 'Sun Jan 28 2018 12:12:55 GMT+0000 (UTC)',
          lastConnection: 'Thu Mar 04 2021 05:52:20 GMT+0000 (UTC)',
        },
        {
          _id: '60abca874677b76a6c2e71ac',
          isActive: true,
          age: 49,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Mariana',
            last: 'Porter',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Mariana+Porter&rounded=true&size=24&background=random',
          company: 'BOVIS',
          email: 'mariana.porter@bovis.co.uk',
          phone: '+33 (847) 596-3050',
          address: '659 Vandam Street, Winston, Wisconsin, 7352',
          registered: 'Thu Nov 22 2018 23:42:09 GMT+0000 (UTC)',
          lastConnection: 'Sun Jan 10 2021 10:00:17 GMT+0000 (UTC)',
        },
        {
          _id: '60abca870d6048f5acad08e5',
          isActive: true,
          age: 37,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Lilly',
            last: 'Hodge',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Lilly+Hodge&rounded=true&size=24&background=random',
          company: 'CHORIZON',
          email: 'lilly.hodge@chorizon.me',
          phone: '+33 (913) 486-3481',
          address: '784 Legion Street, Kennedyville, Colorado, 2484',
          registered: 'Wed Feb 20 2019 04:31:49 GMT+0000 (UTC)',
          lastConnection: 'Wed Mar 03 2021 09:26:37 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87019b932dea7e9cca',
          isActive: true,
          age: 36,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Little',
            last: 'Ortega',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Little+Ortega&rounded=true&size=24&background=random',
          company: 'PYRAMI',
          email: 'little.ortega@pyrami.us',
          phone: '+33 (863) 553-2931',
          address: '713 Lyme Avenue, Onton, North Dakota, 876',
          registered: 'Tue Oct 09 2018 17:54:44 GMT+0000 (UTC)',
          lastConnection: 'Mon May 17 2021 10:00:26 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87eef8351e3b836fcc',
          isActive: false,
          age: 40,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Smith',
            last: 'Horton',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Smith+Horton&rounded=true&size=24&background=random',
          company: 'ISOLOGIX',
          email: 'smith.horton@isologix.info',
          phone: '+33 (935) 487-2646',
          address: '363 High Street, Bentonville, Delaware, 9247',
          registered: 'Sat Aug 11 2018 09:34:59 GMT+0000 (UTC)',
          lastConnection: 'Fri Apr 09 2021 17:38:11 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87876519f68ab1e6b7',
          isActive: false,
          age: 35,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Stone',
            last: 'King',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Stone+King&rounded=true&size=24&background=random',
          company: 'BIOTICA',
          email: 'stone.king@biotica.net',
          phone: '+33 (991) 546-3733',
          address: '512 Cooke Court, Laurelton, Northern Mariana Islands, 2560',
          registered: 'Sat Mar 31 2018 11:53:35 GMT+0000 (UTC)',
          lastConnection: 'Sat Mar 20 2021 05:50:26 GMT+0000 (UTC)',
        },
        {
          _id: '60abca878dbe7116215738a4',
          isActive: true,
          age: 28,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Thornton',
            last: 'Garrett',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Thornton+Garrett&rounded=true&size=24&background=random',
          company: 'TRASOLA',
          email: 'thornton.garrett@trasola.biz',
          phone: '+33 (921) 526-2112',
          address: '864 Vanderveer Place, Bordelonville, Oregon, 9657',
          registered: 'Fri May 11 2018 07:02:49 GMT+0000 (UTC)',
          lastConnection: 'Sat Mar 27 2021 21:46:43 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87145b39d57a8294e4',
          isActive: true,
          age: 32,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Bertha',
            last: 'Hahn',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Bertha+Hahn&rounded=true&size=24&background=random',
          company: 'ZAPPIX',
          email: 'bertha.hahn@zappix.biz',
          phone: '+33 (815) 538-3312',
          address: '326 Rutland Road, Staples, New Hampshire, 2922',
          registered: 'Sat Jul 21 2018 19:32:35 GMT+0000 (UTC)',
          lastConnection: 'Wed May 05 2021 07:58:40 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8728f9ed0624310c7f',
          isActive: true,
          age: 22,
          eyeColor: 'brown',
          job: 'sales',
          name: {
            first: 'Goodwin',
            last: 'Bishop',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Goodwin+Bishop&rounded=true&size=24&background=random',
          company: 'DIGIPRINT',
          email: 'goodwin.bishop@digiprint.io',
          phone: '+33 (968) 516-3267',
          address: '572 Hendrickson Place, Escondida, Marshall Islands, 2612',
          registered: 'Fri Mar 01 2019 07:36:58 GMT+0000 (UTC)',
          lastConnection: 'Mon Apr 26 2021 09:59:57 GMT+0000 (UTC)',
        },
        {
          _id: '60abca871ffbe8176f0fc981',
          isActive: false,
          age: 22,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Conway',
            last: 'Lloyd',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Conway+Lloyd&rounded=true&size=24&background=random',
          company: 'TURNLING',
          email: 'conway.lloyd@turnling.com',
          phone: '+33 (813) 480-3479',
          address: '308 Harrison Place, Rivers, Puerto Rico, 5765',
          registered: 'Thu May 30 2019 21:48:53 GMT+0000 (UTC)',
          lastConnection: 'Tue Jan 19 2021 22:16:20 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8726b38038cdb0665e',
          isActive: false,
          age: 30,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Hazel',
            last: 'Berger',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Hazel+Berger&rounded=true&size=24&background=random',
          company: 'QABOOS',
          email: 'hazel.berger@qaboos.tv',
          phone: '+33 (957) 566-2125',
          address: '853 Colonial Road, Hatteras, Federated States Of Micronesia, 7537',
          registered: 'Tue Oct 29 2019 02:56:38 GMT+0000 (UTC)',
          lastConnection: 'Fri May 07 2021 11:38:29 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87c880435906f82474',
          isActive: false,
          age: 23,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Shields',
            last: 'Warner',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Shields+Warner&rounded=true&size=24&background=random',
          company: 'XERONK',
          email: 'shields.warner@xeronk.ca',
          phone: '+33 (915) 438-3772',
          address: '536 Sullivan Place, Marne, Alabama, 2330',
          registered: 'Tue Apr 02 2019 10:02:18 GMT+0000 (UTC)',
          lastConnection: 'Sun Apr 11 2021 17:22:17 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87906ec5f80fcac197',
          isActive: false,
          age: 27,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Palmer',
            last: 'Daugherty',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Palmer+Daugherty&rounded=true&size=24&background=random',
          company: 'ZENSURE',
          email: 'palmer.daugherty@zensure.name',
          phone: '+33 (877) 569-2210',
          address: '267 Cheever Place, Brule, New Mexico, 4241',
          registered: 'Tue Jul 24 2018 13:23:18 GMT+0000 (UTC)',
          lastConnection: 'Tue Feb 16 2021 11:07:19 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87a1211eb429592669',
          isActive: true,
          age: 22,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Tabatha',
            last: 'Watson',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Tabatha+Watson&rounded=true&size=24&background=random',
          company: 'BARKARAMA',
          email: 'tabatha.watson@barkarama.co.uk',
          phone: '+33 (823) 555-2994',
          address: '363 Cranberry Street, Brenton, South Dakota, 3928',
          registered: 'Sat Jun 16 2018 02:47:37 GMT+0000 (UTC)',
          lastConnection: 'Mon Apr 26 2021 18:36:31 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87f7935edc684bfa9d',
          isActive: true,
          age: 42,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Hardin',
            last: 'Riddle',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Hardin+Riddle&rounded=true&size=24&background=random',
          company: 'BICOL',
          email: 'hardin.riddle@bicol.me',
          phone: '+33 (837) 564-2374',
          address: '236 Elmwood Avenue, Falmouth, Maryland, 7218',
          registered: 'Wed Jan 10 2018 00:51:17 GMT+0000 (UTC)',
          lastConnection: 'Fri Mar 12 2021 06:16:27 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87a3885d5732631b27',
          isActive: true,
          age: 43,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Catherine',
            last: 'Gill',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Catherine+Gill&rounded=true&size=24&background=random',
          company: 'QUIZKA',
          email: 'catherine.gill@quizka.us',
          phone: '+33 (897) 562-2213',
          address: '292 Kings Place, Woodruff, Mississippi, 3217',
          registered: 'Wed Apr 03 2019 22:46:40 GMT+0000 (UTC)',
          lastConnection: 'Thu May 20 2021 09:01:15 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8782cf266f50219315',
          isActive: false,
          age: 30,
          eyeColor: 'blue',
          job: 'designer',
          name: {
            first: 'Lynch',
            last: 'Bullock',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Lynch+Bullock&rounded=true&size=24&background=random',
          company: 'AQUASURE',
          email: 'lynch.bullock@aquasure.info',
          phone: '+33 (853) 408-3648',
          address: '421 Sapphire Street, Wheatfields, Hawaii, 2809',
          registered: 'Fri Dec 14 2018 12:27:27 GMT+0000 (UTC)',
          lastConnection: 'Tue Mar 23 2021 17:10:30 GMT+0000 (UTC)',
        },
        {
          _id: '60abca871d1089550e285f3c',
          isActive: false,
          age: 34,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Patricia',
            last: 'Bauer',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Patricia+Bauer&rounded=true&size=24&background=random',
          company: 'ADORNICA',
          email: 'patricia.bauer@adornica.net',
          phone: '+33 (826) 445-3077',
          address: '935 Rose Street, Chautauqua, District Of Columbia, 3369',
          registered: 'Thu Jun 21 2018 16:03:29 GMT+0000 (UTC)',
          lastConnection: 'Fri Jan 08 2021 21:23:26 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8744d20007726e5f4a',
          isActive: true,
          age: 27,
          eyeColor: 'brown',
          job: 'sales',
          name: {
            first: 'Charlene',
            last: 'Warren',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Charlene+Warren&rounded=true&size=24&background=random',
          company: 'REALYSIS',
          email: 'charlene.warren@realysis.biz',
          phone: '+33 (918) 545-3145',
          address: '132 McKibbin Street, Caberfae, Oklahoma, 1730',
          registered: 'Mon Jun 18 2018 03:14:31 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 08 2021 00:38:10 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87269f400f7a6960af',
          isActive: true,
          age: 43,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Gallegos',
            last: 'Parsons',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Gallegos+Parsons&rounded=true&size=24&background=random',
          company: 'HELIXO',
          email: 'gallegos.parsons@helixo.biz',
          phone: '+33 (830) 535-2855',
          address: '190 Withers Street, Williston, Utah, 226',
          registered: 'Fri Jan 19 2018 07:44:50 GMT+0000 (UTC)',
          lastConnection: 'Mon Mar 08 2021 10:34:31 GMT+0000 (UTC)',
        },
        {
          _id: '60abca871e53be968c79042d',
          isActive: false,
          age: 22,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Bernadine',
            last: 'Barron',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Bernadine+Barron&rounded=true&size=24&background=random',
          company: 'PHOLIO',
          email: 'bernadine.barron@pholio.io',
          phone: '+33 (861) 593-3223',
          address: '204 Euclid Avenue, Fivepointville, Louisiana, 1294',
          registered: 'Wed Aug 07 2019 21:30:11 GMT+0000 (UTC)',
          lastConnection: 'Tue May 04 2021 16:39:01 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8705fd2135aada2bc4',
          isActive: false,
          age: 47,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Hyde',
            last: 'Rocha',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Hyde+Rocha&rounded=true&size=24&background=random',
          company: 'QUILCH',
          email: 'hyde.rocha@quilch.com',
          phone: '+33 (931) 538-2990',
          address: '439 Hart Place, Brownlee, Maine, 6786',
          registered: 'Wed Oct 30 2019 02:27:42 GMT+0000 (UTC)',
          lastConnection: 'Fri Apr 23 2021 15:46:31 GMT+0000 (UTC)',
        },
        {
          _id: '60abca879b61b65e48cfe27d',
          isActive: true,
          age: 50,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Janis',
            last: 'Meyer',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Janis+Meyer&rounded=true&size=24&background=random',
          company: 'OPPORTECH',
          email: 'janis.meyer@opportech.tv',
          phone: '+33 (908) 535-3910',
          address: '499 President Street, Villarreal, South Carolina, 6225',
          registered: 'Fri Dec 13 2019 19:44:07 GMT+0000 (UTC)',
          lastConnection: 'Tue Feb 23 2021 09:21:41 GMT+0000 (UTC)',
        },
        {
          _id: '60abca872bf4f80d434f6ad8',
          isActive: true,
          age: 37,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Jackson',
            last: 'Middleton',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Jackson+Middleton&rounded=true&size=24&background=random',
          company: 'GEOSTELE',
          email: 'jackson.middleton@geostele.ca',
          phone: '+33 (807) 591-2172',
          address: '712 Ditmas Avenue, Kapowsin, West Virginia, 3194',
          registered: 'Tue May 01 2018 19:40:14 GMT+0000 (UTC)',
          lastConnection: 'Fri Mar 26 2021 12:23:06 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87a9d60c3341024d22',
          isActive: false,
          age: 39,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Alisa',
            last: 'Pickett',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Alisa+Pickett&rounded=true&size=24&background=random',
          company: 'NETUR',
          email: 'alisa.pickett@netur.name',
          phone: '+33 (982) 424-3514',
          address: '837 Fulton Street, Joes, North Carolina, 1395',
          registered: 'Fri Jan 12 2018 21:16:30 GMT+0000 (UTC)',
          lastConnection: 'Thu Mar 04 2021 20:03:27 GMT+0000 (UTC)',
        },
        {
          _id: '60abca876f97e7a3e147617a',
          isActive: false,
          age: 36,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Mclaughlin',
            last: 'Wiggins',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Mclaughlin+Wiggins&rounded=true&size=24&background=random',
          company: 'ZUVY',
          email: 'mclaughlin.wiggins@zuvy.co.uk',
          phone: '+33 (926) 491-3701',
          address: '601 Strong Place, Newcastle, Rhode Island, 7716',
          registered: 'Fri Dec 06 2019 15:07:54 GMT+0000 (UTC)',
          lastConnection: 'Sun Feb 07 2021 05:48:53 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87dca37a534990b32f',
          isActive: true,
          age: 39,
          eyeColor: 'brown',
          job: 'humanResources',
          name: {
            first: 'Burgess',
            last: 'Stewart',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Burgess+Stewart&rounded=true&size=24&background=random',
          company: 'BEZAL',
          email: 'burgess.stewart@bezal.me',
          phone: '+33 (911) 501-2997',
          address: '860 Stuart Street, Beaverdale, Florida, 1062',
          registered: 'Wed Feb 21 2018 16:18:48 GMT+0000 (UTC)',
          lastConnection: 'Wed Mar 31 2021 00:12:21 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87ecd6b3cde74331dc',
          isActive: true,
          age: 31,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Bryan',
            last: 'Curry',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Bryan+Curry&rounded=true&size=24&background=random',
          company: 'SURELOGIC',
          email: 'bryan.curry@surelogic.us',
          phone: '+33 (944) 421-2966',
          address: '101 Crosby Avenue, Tecolotito, Connecticut, 2719',
          registered: 'Mon Sep 24 2018 12:54:48 GMT+0000 (UTC)',
          lastConnection: 'Sat Feb 27 2021 12:28:57 GMT+0000 (UTC)',
        },
        {
          _id: '60abca872f8f9c750f92812e',
          isActive: true,
          age: 37,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Rush',
            last: 'Mccormick',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Rush+Mccormick&rounded=true&size=24&background=random',
          company: 'URBANSHEE',
          email: 'rush.mccormick@urbanshee.info',
          phone: '+33 (875) 521-2634',
          address: '370 Visitation Place, Nutrioso, Alaska, 2829',
          registered: 'Mon Nov 12 2018 03:14:49 GMT+0000 (UTC)',
          lastConnection: 'Fri Jan 22 2021 08:27:32 GMT+0000 (UTC)',
        },
        {
          _id: '60abca872687b57e5cc9c7bb',
          isActive: false,
          age: 45,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Betsy',
            last: 'Carter',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Betsy+Carter&rounded=true&size=24&background=random',
          company: 'MUSIX',
          email: 'betsy.carter@musix.net',
          phone: '+33 (997) 445-3419',
          address: '803 Columbia Place, Catharine, Massachusetts, 2895',
          registered: 'Sat Jan 12 2019 18:07:56 GMT+0000 (UTC)',
          lastConnection: 'Tue Apr 20 2021 01:01:12 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87584e47a11b86c081',
          isActive: false,
          age: 37,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Glenn',
            last: 'Morgan',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Glenn+Morgan&rounded=true&size=24&background=random',
          company: 'TEMORAK',
          email: 'glenn.morgan@temorak.biz',
          phone: '+33 (872) 541-3948',
          address: '937 Colby Court, Lemoyne, Arkansas, 7215',
          registered: 'Sat Mar 17 2018 14:10:29 GMT+0000 (UTC)',
          lastConnection: 'Tue Mar 16 2021 14:40:01 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87d406fd5d31c333a4',
          isActive: true,
          age: 25,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Tara',
            last: 'Bartlett',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Tara+Bartlett&rounded=true&size=24&background=random',
          company: 'FUTURIS',
          email: 'tara.bartlett@futuris.biz',
          phone: '+33 (887) 529-3949',
          address: '919 Garland Court, Warren, Nebraska, 1876',
          registered: 'Sat Jun 30 2018 03:25:24 GMT+0000 (UTC)',
          lastConnection: 'Fri May 21 2021 01:01:37 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87ed9609f31eae3e26',
          isActive: false,
          age: 46,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Meyer',
            last: 'Frank',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Meyer+Frank&rounded=true&size=24&background=random',
          company: 'ACUSAGE',
          email: 'meyer.frank@acusage.io',
          phone: '+33 (977) 440-2359',
          address: '728 Bevy Court, Ezel, Virginia, 5329',
          registered: 'Tue Jan 23 2018 08:21:56 GMT+0000 (UTC)',
          lastConnection: 'Mon May 03 2021 12:17:11 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87e862cb3739db3188',
          isActive: false,
          age: 26,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Anne',
            last: 'Lang',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Anne+Lang&rounded=true&size=24&background=random',
          company: 'TWIGGERY',
          email: 'anne.lang@twiggery.com',
          phone: '+33 (919) 532-3159',
          address: '427 Caton Avenue, Harleigh, Minnesota, 8519',
          registered: 'Wed Dec 26 2018 19:23:38 GMT+0000 (UTC)',
          lastConnection: 'Sun Mar 14 2021 12:47:10 GMT+0000 (UTC)',
        },
        {
          _id: '60abca877039dedfc60a7444',
          isActive: false,
          age: 44,
          eyeColor: 'green',
          job: 'sales',
          name: {
            first: 'Cote',
            last: 'Nielsen',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Cote+Nielsen&rounded=true&size=24&background=random',
          company: 'EXOSPEED',
          email: 'cote.nielsen@exospeed.tv',
          phone: '+33 (878) 495-2651',
          address: '703 Harbor Lane, Strong, New Jersey, 1430',
          registered: 'Fri May 31 2019 23:26:09 GMT+0000 (UTC)',
          lastConnection: 'Fri Feb 26 2021 12:20:43 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8798c065ac8bfcb0cc',
          isActive: false,
          age: 38,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Selena',
            last: 'Castro',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Selena+Castro&rounded=true&size=24&background=random',
          company: 'LOCAZONE',
          email: 'selena.castro@locazone.ca',
          phone: '+33 (980) 584-2687',
          address: '824 Veterans Avenue, Como, Illinois, 3543',
          registered: 'Sat Mar 10 2018 19:49:27 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 08 2021 04:15:17 GMT+0000 (UTC)',
        },
        {
          _id: '60abca871abc16da2db868a8',
          isActive: true,
          age: 28,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Rosemarie',
            last: 'Hunter',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Rosemarie+Hunter&rounded=true&size=24&background=random',
          company: 'XYMONK',
          email: 'rosemarie.hunter@xymonk.name',
          phone: '+33 (803) 464-2942',
          address: '692 Highland Avenue, Salix, Kentucky, 6781',
          registered: 'Sat May 05 2018 12:47:39 GMT+0000 (UTC)',
          lastConnection: 'Tue Feb 23 2021 17:51:01 GMT+0000 (UTC)',
        },
        {
          _id: '60abca875cf40e9f052226b0',
          isActive: false,
          age: 49,
          eyeColor: 'brown',
          job: 'designer',
          name: {
            first: 'Rosetta',
            last: 'Montoya',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Rosetta+Montoya&rounded=true&size=24&background=random',
          company: 'QUANTALIA',
          email: 'rosetta.montoya@quantalia.co.uk',
          phone: '+33 (844) 461-2065',
          address: '292 Erskine Loop, Belva, New York, 3737',
          registered: 'Sun Feb 18 2018 21:08:24 GMT+0000 (UTC)',
          lastConnection: 'Fri Feb 12 2021 16:52:00 GMT+0000 (UTC)',
        },
        {
          _id: '60abca871c20b767646bc389',
          isActive: true,
          age: 41,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Vaughn',
            last: 'Wheeler',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Vaughn+Wheeler&rounded=true&size=24&background=random',
          company: 'SENTIA',
          email: 'vaughn.wheeler@sentia.me',
          phone: '+33 (850) 413-2038',
          address: '875 Pershing Loop, Cannondale, Tennessee, 3669',
          registered: 'Tue May 15 2018 22:39:23 GMT+0000 (UTC)',
          lastConnection: 'Thu Apr 22 2021 07:52:39 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87081570173c801996',
          isActive: true,
          age: 24,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Frances',
            last: 'Campbell',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Frances+Campbell&rounded=true&size=24&background=random',
          company: 'ISONUS',
          email: 'frances.campbell@isonus.us',
          phone: '+33 (818) 414-2540',
          address: '474 Mill Avenue, Blanco, Wyoming, 7225',
          registered: 'Sat Jul 13 2019 04:05:07 GMT+0000 (UTC)',
          lastConnection: 'Wed Jan 27 2021 01:40:26 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87df11c9c5e9b9716f',
          isActive: true,
          age: 50,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Dotson',
            last: 'Rhodes',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Dotson+Rhodes&rounded=true&size=24&background=random',
          company: 'IMAGEFLOW',
          email: 'dotson.rhodes@imageflow.info',
          phone: '+33 (924) 429-3617',
          address: '505 Ellery Street, Hoagland, Idaho, 3116',
          registered: 'Thu Feb 22 2018 12:38:58 GMT+0000 (UTC)',
          lastConnection: 'Mon Mar 22 2021 21:05:14 GMT+0000 (UTC)',
        },
        {
          _id: '60abca873e2b902053a06784',
          isActive: false,
          age: 22,
          eyeColor: 'green',
          job: 'designer',
          name: {
            first: 'Lloyd',
            last: 'Yates',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Lloyd+Yates&rounded=true&size=24&background=random',
          company: 'PROVIDCO',
          email: 'lloyd.yates@providco.net',
          phone: '+33 (965) 408-2159',
          address: '797 Ocean Avenue, Canby, Georgia, 6173',
          registered: 'Sat May 04 2019 15:09:26 GMT+0000 (UTC)',
          lastConnection: 'Tue Jan 12 2021 17:51:02 GMT+0000 (UTC)',
        },
        {
          _id: '60abca871fbd2e458c82eea7',
          isActive: true,
          age: 38,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Karla',
            last: 'Walker',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Karla+Walker&rounded=true&size=24&background=random',
          company: 'CORMORAN',
          email: 'karla.walker@cormoran.biz',
          phone: '+33 (888) 527-2214',
          address: '341 Halleck Street, Gerton, Indiana, 5501',
          registered: 'Wed Mar 06 2019 19:09:34 GMT+0000 (UTC)',
          lastConnection: 'Mon Mar 29 2021 13:46:30 GMT+0000 (UTC)',
        },
        {
          _id: '60abca874231db53f145c5db',
          isActive: false,
          age: 36,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Carly',
            last: 'Mckinney',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Carly+Mckinney&rounded=true&size=24&background=random',
          company: 'DEVILTOE',
          email: 'carly.mckinney@deviltoe.biz',
          phone: '+33 (877) 548-3148',
          address: '307 Knapp Street, Marbury, California, 6165',
          registered: 'Sun Jul 15 2018 10:43:18 GMT+0000 (UTC)',
          lastConnection: 'Tue Mar 30 2021 21:56:51 GMT+0000 (UTC)',
        },
        {
          _id: '60abca875d718373c20d2c6e',
          isActive: true,
          age: 45,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Paige',
            last: 'Blackwell',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Paige+Blackwell&rounded=true&size=24&background=random',
          company: 'CORIANDER',
          email: 'paige.blackwell@coriander.io',
          phone: '+33 (862) 449-3431',
          address: '428 Seabring Street, Whipholt, Pennsylvania, 1651',
          registered: 'Sun Mar 24 2019 15:03:17 GMT+0000 (UTC)',
          lastConnection: 'Mon Apr 19 2021 10:16:56 GMT+0000 (UTC)',
        },
        {
          _id: '60abca876eb03156840d8df0',
          isActive: false,
          age: 43,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Violet',
            last: 'Garcia',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Violet+Garcia&rounded=true&size=24&background=random',
          company: 'ZOLAVO',
          email: 'violet.garcia@zolavo.com',
          phone: '+33 (856) 403-3565',
          address: '506 Story Street, Hall, Virgin Islands, 2912',
          registered: 'Thu Jul 26 2018 01:12:28 GMT+0000 (UTC)',
          lastConnection: 'Sat May 08 2021 12:04:24 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8731063466573b4d20',
          isActive: false,
          age: 21,
          eyeColor: 'blue',
          job: 'designer',
          name: {
            first: 'Albert',
            last: 'Dalton',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Albert+Dalton&rounded=true&size=24&background=random',
          company: 'XYLAR',
          email: 'albert.dalton@xylar.tv',
          phone: '+33 (965) 530-2584',
          address: '646 Clay Street, Austinburg, Texas, 6983',
          registered: 'Fri Jul 20 2018 13:07:50 GMT+0000 (UTC)',
          lastConnection: 'Sat Mar 13 2021 06:41:11 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87b627a66e0ffb0d46',
          isActive: false,
          age: 46,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Penny',
            last: 'Russo',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Penny+Russo&rounded=true&size=24&background=random',
          company: 'DATAGEN',
          email: 'penny.russo@datagen.ca',
          phone: '+33 (844) 494-3091',
          address: '487 Merit Court, Vincent, Michigan, 7453',
          registered: 'Sun Dec 01 2019 11:08:20 GMT+0000 (UTC)',
          lastConnection: 'Sat Feb 20 2021 04:48:29 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87d3690d40988dbb87',
          isActive: false,
          age: 37,
          eyeColor: 'green',
          job: 'developer',
          name: {
            first: 'Dorothy',
            last: 'Blake',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Dorothy+Blake&rounded=true&size=24&background=random',
          company: 'ROTODYNE',
          email: 'dorothy.blake@rotodyne.name',
          phone: '+33 (940) 594-3436',
          address: '561 Alice Court, Keller, Arizona, 8100',
          registered: 'Mon Sep 24 2018 09:21:12 GMT+0000 (UTC)',
          lastConnection: 'Sun Jan 24 2021 22:05:05 GMT+0000 (UTC)',
        },
        {
          _id: '60abca873321ee9658a0b3dc',
          isActive: true,
          age: 40,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Maryanne',
            last: 'Bridges',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Maryanne+Bridges&rounded=true&size=24&background=random',
          company: 'COLLAIRE',
          email: 'maryanne.bridges@collaire.co.uk',
          phone: '+33 (994) 400-3184',
          address: '264 Manhattan Court, Rose, Nevada, 1454',
          registered: 'Fri Aug 30 2019 19:30:48 GMT+0000 (UTC)',
          lastConnection: 'Fri Jan 01 2021 17:09:21 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8728e603807ad111ab',
          isActive: false,
          age: 32,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Belinda',
            last: 'Cardenas',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Belinda+Cardenas&rounded=true&size=24&background=random',
          company: 'GOLISTIC',
          email: 'belinda.cardenas@golistic.me',
          phone: '+33 (920) 466-2448',
          address: '507 Degraw Street, Shindler, Ohio, 9819',
          registered: 'Tue Dec 31 2019 21:41:57 GMT+0000 (UTC)',
          lastConnection: 'Wed Jan 06 2021 19:38:45 GMT+0000 (UTC)',
        },
        {
          _id: '60abca870f0e13194bb3563b',
          isActive: false,
          age: 22,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Travis',
            last: 'Griffith',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Travis+Griffith&rounded=true&size=24&background=random',
          company: 'FOSSIEL',
          email: 'travis.griffith@fossiel.us',
          phone: '+33 (840) 528-3079',
          address: '669 Claver Place, Ladera, Guam, 2261',
          registered: 'Fri Aug 10 2018 04:31:48 GMT+0000 (UTC)',
          lastConnection: 'Wed Jan 27 2021 09:21:59 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8727e24d278c73d1cb',
          isActive: false,
          age: 45,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Chen',
            last: 'Mayo',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Chen+Mayo&rounded=true&size=24&background=random',
          company: 'KEENGEN',
          email: 'chen.mayo@keengen.info',
          phone: '+33 (987) 557-2020',
          address: '143 Aberdeen Street, Loveland, Montana, 9793',
          registered: 'Thu Oct 31 2019 09:20:24 GMT+0000 (UTC)',
          lastConnection: 'Thu Apr 15 2021 07:48:36 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87d93e0d0d8b63f577',
          isActive: false,
          age: 44,
          eyeColor: 'blue',
          job: 'humanResources',
          name: {
            first: 'Samantha',
            last: 'Holloway',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Samantha+Holloway&rounded=true&size=24&background=random',
          company: 'BOILCAT',
          email: 'samantha.holloway@boilcat.net',
          phone: '+33 (928) 551-2679',
          address: '159 Dunne Court, Wikieup, Missouri, 9732',
          registered: 'Wed May 08 2019 07:19:00 GMT+0000 (UTC)',
          lastConnection: 'Sun Jan 24 2021 00:13:12 GMT+0000 (UTC)',
        },
        {
          _id: '60abca879f6c424b5a95015f',
          isActive: false,
          age: 47,
          eyeColor: 'green',
          job: 'humanResources',
          name: {
            first: 'Miller',
            last: 'Blackburn',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Miller+Blackburn&rounded=true&size=24&background=random',
          company: 'ORBIN',
          email: 'miller.blackburn@orbin.biz',
          phone: '+33 (838) 429-3415',
          address: '963 Berriman Street, Graniteville, Vermont, 1305',
          registered: 'Mon Mar 11 2019 06:41:50 GMT+0000 (UTC)',
          lastConnection: 'Mon Feb 01 2021 03:40:15 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87e468c2a3064bd2e7',
          isActive: false,
          age: 21,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Traci',
            last: 'Anthony',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Traci+Anthony&rounded=true&size=24&background=random',
          company: 'UNCORP',
          email: 'traci.anthony@uncorp.biz',
          phone: '+33 (974) 451-3636',
          address: '350 Cropsey Avenue, Sims, Washington, 9857',
          registered: 'Wed Jan 30 2019 22:59:34 GMT+0000 (UTC)',
          lastConnection: 'Fri Feb 19 2021 10:09:48 GMT+0000 (UTC)',
        },
        {
          _id: '60abca878b30fd5f496386f3',
          isActive: true,
          age: 31,
          eyeColor: 'brown',
          job: 'developer',
          name: {
            first: 'Ferguson',
            last: 'Hanson',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Ferguson+Hanson&rounded=true&size=24&background=random',
          company: 'QUAREX',
          email: 'ferguson.hanson@quarex.io',
          phone: '+33 (838) 477-2684',
          address: '326 Newkirk Placez, Olney, American Samoa, 2337',
          registered: 'Sat Dec 21 2019 20:10:28 GMT+0000 (UTC)',
          lastConnection: 'Mon May 03 2021 15:55:40 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8763fbb4708bc8392b',
          isActive: true,
          age: 47,
          eyeColor: 'blue',
          job: 'developer',
          name: {
            first: 'Powell',
            last: 'Perez',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Powell+Perez&rounded=true&size=24&background=random',
          company: 'QUONATA',
          email: 'powell.perez@quonata.com',
          phone: '+33 (808) 439-4000',
          address: '468 Bergen Avenue, Johnsonburg, Kansas, 2753',
          registered: 'Tue Oct 15 2019 12:18:43 GMT+0000 (UTC)',
          lastConnection: 'Mon May 17 2021 21:20:50 GMT+0000 (UTC)',
        },
        {
          _id: '60abca8738f4c1157ff7a7e2',
          isActive: true,
          age: 45,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Vanessa',
            last: 'Underwood',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Vanessa+Underwood&rounded=true&size=24&background=random',
          company: 'EARBANG',
          email: 'vanessa.underwood@earbang.tv',
          phone: '+33 (946) 564-2774',
          address: '401 Virginia Place, Fairfield, Palau, 834',
          registered: 'Wed Jun 13 2018 08:27:44 GMT+0000 (UTC)',
          lastConnection: 'Sat Jan 23 2021 05:07:27 GMT+0000 (UTC)',
        },
        {
          _id: '60abca87b245b3be92dd43b2',
          isActive: true,
          age: 49,
          eyeColor: 'blue',
          job: 'sales',
          name: {
            first: 'Douglas',
            last: 'Walters',
          },
          avatar: 'https://eu.ui-avatars.com/api/?name=Douglas+Walters&rounded=true&size=24&background=random',
          company: 'GEEKUS',
          email: 'douglas.walters@geekus.ca',
          phone: '+33 (820) 449-3118',
          address: '761 Richards Street, Gorst, Wisconsin, 142',
          registered: 'Sat Feb 24 2018 21:51:54 GMT+0000 (UTC)',
          lastConnection: 'Fri Mar 26 2021 08:03:10 GMT+0000 (UTC)',
        },
      ],
    }
  },
}
</script>

<style lang="scss" scoped>
.table {
  /* Rajouter le SCSS manquant pour styliser le contenu du tableau */
}
</style>
